Repository AlecThomson/RACS-tools, pull requests merged in 2022-12, with the labels that each got.

#21 Better main args
  racs_tools/beamcon_2D.py
  racs_tools/beamcon_3D.py
  setup.py
Labels: bug, enhancement

#23 Refactor getnoise
  README.md
  racs_tools/au2.py
  racs_tools/beamcon_2D.py
  racs_tools/beamcon_3D.py
  racs_tools/convolve_uv.py
  racs_tools/getnoise_list.py
  setup.py
Labels: bug, documentation

#24 Ignore BeamError in deconvolve check where target_beam=beam
  racs_tools/beamcon_2D.py
Labels: bug
